---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.app.storage.name }}
spec:
  accessModes:
    - {{ .Values.app.storage.access }}
  storageClassName: {{ .Values.app.storage.class }}
  resources:
    requests:
      storage: {{ .Values.app.storage.size }}
