app:
  image:
    version: 7.5.9
    pullPolicy: IfNotPresent

  storage:
    name: "grafana-managed-disk"
    class: "azurefile-premium-retain"
    size: "100Gi"
    access: "ReadWriteMany"

ingress:
  enabled: true
  enableTLS: true
